version: '3.9'

services:
  api:
    build:
      target: dev
    container_name: ecommerce-api-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/backend/src:/app/apps/backend/src:cached
      - ./apps/backend/tsconfig.json:/app/apps/backend/tsconfig.json:cached
      - ./apps/backend/nest-cli.json:/app/apps/backend/nest-cli.json:cached
      - /app/node_modules
      - /app/apps/backend/node_modules
    command: npm run start:dev
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    ports:
      - "5432:5432"