services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: ecommerce-api-dev
    ports:
      - '3000:3000'
    env_file:
      - ./apps/backend/.env
    environment:
      NODE_ENV: development
      WORKER_MODE: 'false'
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 1000
      WATCHPACK_POLLING: 'true'
      WATCHPACK_POLLING_INTERVAL: 1000
      TSC_WATCHFILE: DynamicPriorityPolling
      TSC_WATCHDIRECTORY: DynamicPriorityPolling
      TSC_NONPOLLING_WATCHER: 'false'
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/node_modules
      - /app/apps/backend/node_modules
    command: npm run start:dev
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal
      - public

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: ecommerce-worker-dev
    env_file:
      - ./apps/backend/.env
    environment:
      NODE_ENV: development
      WORKER_MODE: 'true'
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 1000
      WATCHPACK_POLLING: 'true'
      WATCHPACK_POLLING_INTERVAL: 1000
      TSC_WATCHFILE: DynamicPriorityPolling
      TSC_WATCHDIRECTORY: DynamicPriorityPolling
      TSC_NONPOLLING_WATCHER: 'false'
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/node_modules
      - /app/apps/backend/node_modules
    command: npm run start:dev
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      target: dev
    container_name: ecommerce-frontend-dev
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      BACKEND_URL: http://api:3000
      NEXT_PUBLIC_API_URL: http://api:3000
      WATCHPACK_POLLING: 'true'
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./apps/frontend/src:/app/src:cached
      - ./apps/frontend/public:/app/public:cached
      - /app/node_modules
      - /app/.next
    networks:
      - public
      - internal

  postgres:
    ports:
      - '${POSTGRES_DEV_PORT:-15432}:5432'

  rabbitmq:
    ports:
      - '5672:5672'
      - '15672:15672'