import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppBar from "@/components/ui/appBar";
import UserStoreHydrator from "@/components/UserStoreHydrator";
import { getSession } from "@/lib/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserStoreHydrator
          user={
            session?.user
              ? {
                  id: String(session.user.id),
                  name: session.user.name,
                  avatarUrl: session.user.avatarUrl ?? null,
                }
              : null
          }
        />
        <AppBar />
        {children}
      </body>
    </html>
  );
}
