import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppBar from "@/components/ui/appBar";
import UserStoreHydrator from "@/components/UserStoreHydrator";
import { getSession } from "@/lib/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const backendUrl =
    process.env.BACKEND_URL ||
    process.env.NEXT_PUBLIC_BACKEND_URL ||
    'http://api:3000';

  let hydratedUser =
    session?.user
      ? {
          id: String(session.user.id),
          name: session.user.name,
          avatarUrl: session.user.avatarUrl ?? null,
        }
      : null;

  if (session?.user?.id) {
    try {
      const latestUserUrl = session.user.email
        ? `${backendUrl}/user/${encodeURIComponent(session.user.email)}`
        : `${backendUrl}/user/id/${String(session.user.id)}`;

      const response = await fetch(latestUserUrl, { cache: 'no-store' });

      if (response.ok) {
        const latestUser = (await response.json()) as {
          id: string;
          name: string;
          email?: string;
          avatarUrl?: string | null;
          avatarFileId?: string | null;
        };

        let resolvedAvatarUrl = latestUser.avatarUrl ?? null;

        if (latestUser.avatarFileId) {
          const fileUrlResponse = await fetch(
            `${backendUrl}/files/${latestUser.avatarFileId}/url?userId=${encodeURIComponent(
              String(latestUser.id),
            )}`,
            { cache: 'no-store' },
          );

          if (fileUrlResponse.ok) {
            const fileUrlData = (await fileUrlResponse.json()) as { url?: string };
            resolvedAvatarUrl = fileUrlData.url ?? resolvedAvatarUrl;
          }
        }

        hydratedUser = {
          id: String(latestUser.id),
          name: latestUser.name,
          avatarUrl: resolvedAvatarUrl,
        };
      }
    } catch {}
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserStoreHydrator user={hydratedUser} />
        <AppBar />
        {children}
      </body>
    </html>
  );
}
